services:
  - type: web
    name: sangam-railway
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        value: sqlite:///./sangam.db
